tasks:
  tv task:
    rss: $rssFeed
    all_series: yes
    transmission:
      host: localhost
      port: 9091
      ratio: 0
  remove stale torrents:
    disable: [ seen, seen_info_hash ]
    from_transmission:
      host: localhost
      only_complete: yes
      port: 9091
    if:
      - transmission_date_done > now - timedelta(days=2): reject
      - transmission_progress == 100: accept
      - not transmission_seed_ratio_ok: reject
      - not transmission_idle_limit_ok: reject
    regexp:
      reject_excluding:
        - "/data/apps/downloads/completed":
            from: transmission_downloadDir